---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.connect.snapshot.persistentVolumeClaim.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.connect.name }}
    {{- include "confluent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.connect.snapshot.storageClassName.name }}
  resources:
    requests:
      storage: {{ .Values.connect.snapshot.persistentVolumeClaim.storage }}
  dataSource:
    name: {{ .Values.connect.snapshot.name }}
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ .Values.connect.snapshot.name }}
  labels:
    app: {{ .Values.connect.name }}
    {{- include "confluent.labels" . | nindent 4 }}
spec:
  source:
    volumeSnapshotContentName: {{ .Values.connect.snapshot.volumeSnapshotContentName.reference }}
  volumeSnapshotClassName: {{ .Values.connect.snapshot.volumeSnapshotClassName.name }}

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: {{ .Values.connect.snapshot.volumeSnapshotContent.name }}
  labels:
    app: {{ .Values.connect.name }}
    {{- include "confluent.labels" . | nindent 4 }}
spec:
  volumeSnapshotRef:
    kind: VolumeSnapshot
    name: {{ .Values.connect.snapshot.name }}
    namespace: {{ .Values.namespace }}
  source:
    snapshotHandle: {{ .Values.connect.snapshotID }}
  driver: ebs.csi.aws.com
  deletionPolicy: Retain
  volumeSnapshotClassName: {{ .Values.connect.snapshot.volumeSnapshotClassName.name }}
