---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.connect.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.connect.name }}
    {{- include "confluent.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.connect.serviceAccount.role }}