---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: msk-connect-dbdev
  namespace: confluent
  annotations:
    argocd.argoproj.io/sync-wave: "-13"
spec:
  externalSecretName: msk-connect-dbdev
  externalSecretSpec:
    dataFrom:
    - extract:
        key: AmazonMSK_/msk_kafkaconnect_dbdev
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: aws-secrets-manager
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
      name: msk-connect-dbdev
      template:
        engineVersion: v2
        type: Opaque
  namespaceSelector:
    matchLabels:
      amazonmsk: "true"
  refreshTime: 1m

# Password: _*VyE#($_e?W8}ic
# Username: msk_kafkaconnect_dbdev