apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: msk-schemaregistry-dbdev
  namespace: confluent
  annotations:
    argocd.argoproj.io/sync-wave: "-13"
spec:
  externalSecretName: msk-schemaregistry-dbdev
  externalSecretSpec:
    dataFrom:
    - extract:
        key: AmazonMSK_/msk_schemaregistry_dbdev
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: aws-secrets-manager
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
      name: msk-schemaregistry-dbdev
      template:
        engineVersion: v2
        type: Opaque
  namespaceSelector:
    matchLabels:
      amazonmsk: "true"
  refreshTime: 1m

# Creds schema-registry
# msk_schemaregistry_dbdev
# 7][pOf!s2<6Bcz+f