---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb
  namespace: confluent
  labels:
    app: ksqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksqldb
  template:
    metadata:
      labels:
        app: ksqldb
    spec:
      containers:
      - name: ksqldb
        image: confluentinc/cp-ksqldb-server:7.5.0
        ports:
        - containerPort: 8088
        env:
        - name: KSQL_KSQL_SERVICE_ID
          value: "ksqldb-server-dbdev"
        - name: KSQL_LISTERNERS
          value: "http://0.0.0.0:8088"
        - name: KSQL_BOOTSTRAP_SERVERS
          value: b-2.bifrostusvadbdevmskkaf.7929xq.c3.kafka.us-east-1.amazonaws.com:9096,b-1.bifrostusvadbdevmskkaf.7929xq.c3.kafka.us-east-1.amazonaws.com:9096,b-3.bifrostusvadbdevmskkaf.7929xq.c3.kafka.us-east-1.amazonaws.com:9096
        - name: KSQL_SECURITY_PROTOCOL
          value: "SASL_SSL"
        - name: KSQL_SASL_MECHANISM
          value: "SCRAM-SHA-512"
        - name: KSQL_KSQL_CONNECT_URL
          value: "http://connect-svc.confluent.svc.cluster.local:8083"
        - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
          value: "http://schema-registry-svc.confluent.svc.cluster.local:8081"
        - name: KSQL_KSQL_FAIL_ON_DESERIALIZATION_ERROR
          value: "false"
        - name: KSQL_KSQL_FAIL_ON_PRODUCTION_ERROR
          value: "false"
        - name: KSQL_KSQL_INTERNAL_TOPIC_REPLICAS
          value: "-1"
        - name: KSQL_KSQL_STREAMS_REPLICATION_FACTOR
          value: "-1"
        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR
          value: "-1"
        - name: KSQL_HEARTBEAT_ENABLE
          value: "true"
        - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
          value: "true"
        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
          value: "true"
        - name: KSQL_KSQL_SINK_REPLICAS
          value: "3"
        - name: KSQL_KSQL_STREAMS_REPLICATION_FACTOR
          value: "3"
        - name: KSQL_KSQL_INTERNAL_TOPIC_REPLICAS
          value: "3"
        - name: KSQL_CLASSPATH
          value: "/usr/share/java/*:/usr/share/java/ksqldb-server/*"
        - name: KSQL_KSQL_EXTENSION_DIR
          value: "/opt/ksqldb-udfs"
        - name: KSQLDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: msk-ksqldb-dbdev
              key: username
        - name: KSQLDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: msk-ksqldb-dbdev
              key: password
        - name: KSQL_SASL_JAAS_CONFIG
          value: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"$(KSQLDB_USERNAME)\" password=\"$(KSQLDB_PASSWORD)\";"