---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ .Values.connect.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-13"
spec:
  externalSecretName: {{ .Values.connect.secretname}}
  externalSecretSpec:
    dataFrom:
    - extract:
        key: {{ .Values.connect.secretkey}}
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: aws-secrets-manager
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
      name: {{ .Values.connect.secretname}}
      template:
        engineVersion: v2
        type: Opaque
  namespaceSelector:
    matchLabels:
      amazonmsk: "true"
  refreshTime: 1m

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ .Values.schemaregistry.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-13"
spec:
  externalSecretName: {{ .Values.schemaregistry.secretname}}
  externalSecretSpec:
    dataFrom:
    - extract:
        key: {{ .Values.schemaregistry.secretkey}}
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: aws-secrets-manager
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
      name: {{ .Values.schemaregistry.secretname}}
      template:
        engineVersion: v2
        type: Opaque
  namespaceSelector:
    matchLabels:
      amazonmsk: "true"
  refreshTime: 1m

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ .Values.restproxy.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-13"
spec:
  externalSecretName: {{ .Values.restproxy.secretname}}
  externalSecretSpec:
    dataFrom:
    - extract:
        key: {{ .Values.restproxy.secretkey}}
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: aws-secrets-manager
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
      name: {{ .Values.restproxy.secretname}}
      template:
        engineVersion: v2
        type: Opaque
  namespaceSelector:
    matchLabels:
      amazonmsk: "true"
  refreshTime: 1m

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ .Values.ksqldb.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-13"
spec:
  externalSecretName: {{ .Values.ksqldb.secretname}}
  externalSecretSpec:
    dataFrom:
    - extract:
        key: {{ .Values.ksqldb.secretkey}}
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: aws-secrets-manager
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
      name: {{ .Values.ksqldb.secretname}}
      template:
        engineVersion: v2
        type: Opaque
  namespaceSelector:
    matchLabels:
      amazonmsk: "true"
  refreshTime: 1m